* Search and download utility for Sentinel 3 data
This utility ([[./S3Search.sh]]), developed by Maxim Lamare, downloads Sentinel 3 data

The additional scripts are used to fetch unique quicklook images, and then download products based on a folder of quicklook images.

* Usage Instructions:

Example to download a list of Sentinel 3 products (OLCI) covering a specific point (66N, 45W) and time (June 2017):

#+BEGIN_SRC sh :results verbatim :eval no-export
./S3search.sh -i OLCI -s 2017-06-01  -e 2017-07-01 -f 66:-45
#+END_SRC
#+RESULTS:

The result of the above script is a file, =product_IDs.txt=, that contains the quicklook name. From this, we can a) fetch a quicklook file and b) download the full data set.

Fetch quicklook files, for all products listed in =product_IDs.txt= (generated by =S3Search.sh=.

#+BEGIN_SRC sh :results verbatim :eval no-export
./fetch_ql.sh
#+END_SRC
#+RESULTS:

To view all quicklook files. In "Preview.app", CMD+<DELETE> deletes a file.

#+BEGIN_SRC sh :results verbatim :eval no-export
open ./quicklook/*
#+END_SRC
#+RESULTS:

To fetch the full data for all quicklook files in a folder:

#+BEGIN_SRC sh :results verbatim :eval no-export
./fetch_scene_from_ql.sh <quicklook_folder> <target_folder>
#+END_SRC
#+RESULTS:

To fetch every product ID:

#+BEGIN_SRC sh :results verbatim :eval no-export
rm tmp.txt # reset
for year in $(seq 2016 2017); do
  for day0 in $(seq 1 15 366); do # 15 day increments
    day1=$((day0+15))
    date0=$(gdate --date="${year}-01-01 +${day0} days" --iso-8601)
    date1=$(gdate --date="${year}-01-01 +${day1} days" --iso-8601)

    ./S3search.sh -i OLCI -s $date0  -e $date1 -f 66:-45
    cat product_IDs.txt >> tmp.txt # append

    ./S3search.sh -i OLCI -s $date0  -e $date1 -f 76:-42
    cat product_IDs.txt >> tmp.txt

  done
done
mv tmp.txt product_IDs.txt
#+END_SRC
#+RESULTS:

