name: CI
on:
  push:
    branches:
      - master
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC1004 -e SC2068 -e SC2077 -e SC2078 -e SC2145 -e SC2242 
        with:
          severity: error
