name: test-bash
on:
  push:
    branches:
      - master
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        with:
          severity: error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # exclude some shellcheck warnings.
          SHELLCHECK_OPTS: -e SC1004 SC2068 SC2077 SC2078 SC2145 SC2242 
          # arguments to shfmt.
          SHFMT_OPTS: -s 
        with:
          sh_checker_comment: true
          sh_checker_shfmt_disable: true
          # sh_checker_shellcheck_disable: true
